<?php

namespace AppBundle\Repository;

/**
 * RestaurantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RestaurantRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllAssoc(){
        $em = $this->getEntityManager();
        $restaurants = $em->getRepository('AppBundle:Restaurant')->findAll();
        $assocRestaurants = [];
        foreach ($restaurants as $restaurant){
            $key = $restaurant->getName().', '.$restaurant->getAddress();
            $assocRestaurants[$key] = $restaurant;
        }
        return $assocRestaurants;
    }
}
